### PR TITLE
feat(tailwind-eslint): add tailwind eslint plugin

### PR DESCRIPTION
**Pull request by mrtag23**

### CODE REVIEW

**Comment by mrtag23** [comment]
Screenshot 2024-10-30 at 8 49 33 AM

**Review by asgorobets — COMMENTED** [review]
Have you checked if validaiton is done in `cn` functions like asked in the ticket?

> It's important to whitelist cn function (our helper for clsx and tailwind-merge) so that we validate classnames in the helper

**Comment by mrtag23** [comment]
> Have you checked if validaiton is done in `cn` functions like asked in the ticket?
> 
> > It's important to whitelist cn function (our helper for clsx and tailwind-merge) so that we validate classnames in the helper

yes, most of those warnings were generated off the cn function content

**Comment by asgorobets** [comment]
I ended up adding `cn` helper to list of callees [here](https://github.com/jakala-na/next-contentful-starterkit/pull/64/commits/2ba1908b404399e1e33df9f9fccafa0d26665a51#diff-6884918dc8291219be508e05e28965b958c734def85324f3b53858ea4702090fR22) because while className properties were scanned when used directly, if I have a variable with classnames outside of className property, it wasn't validating it, with my change it does that now.

Screenshot 2024-11-02 at 10 10 30 PM

**Review by asgorobets — APPROVED** [review]

**Pull request merged**
